### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by asalbers** [lgmorand/the-aks-checklist#311]
While using the AKS Checklist the checkboxes dont show as marked when you click on an item in it. 

First image below shows an unchecked item:
![beforecheck](https://user-images.githubusercontent.com/7284102/232601095-305f6eab-3ec0-4019-9601-25abae9edc16.png)

This is what I see after I check the box. I noticed the bar goes up 10% but the item does not show as checked. 
![aftercheck](https://user-images.githubusercontent.com/7284102/232601112-6bc07a2d-5529-4e05-b72c-3132dab018e2.png)

**Comment by lgmorand** [comment]
Thanks @asalbers
Fixed, I just need to merge and deploy on the prod env
