### ISSUE TITLE
Add documentation links where missing

### ISSUE THREAD

**Issue by jamesfoster** [lgmorand/the-aks-checklist#314]
https://github.com/lgmorand/the-aks-checklist/blob/134a5857470482db314cd822015bb59b56da18cd/data/en/items/cluster_security.json#L54

https://github.com/lgmorand/the-aks-checklist/blob/134a5857470482db314cd822015bb59b56da18cd/data/en/items/operations.json#L375

https://github.com/lgmorand/the-aks-checklist/blob/134a5857470482db314cd822015bb59b56da18cd/data/en/items/application.json#L459

These are the only 3 items which don’t have links. It would be good to add a link to these even if it is repeated from another item. e.g. you could link to the [Namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/?ref=www.the-aks-checklist.com) page for the “do not use the default namespace” item.

**Comment by lgmorand** [comment]
Hi James

To have links we need content. For instance, dashboard is a secure flaw but nothing explains it. The fact they don't have should not be an issue. but thanks a lot for opening issues, it helps to improve it :)

ps: if you find relevant links, don't hesitate to add them here or do a PR :)
